export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAIL = 'GET_TRENDING_FAIL';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';

export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const GET_FROM_LOCAL = 'GET_FROM_LOCAL';
